git:
  commit:
    signOff: true
  pagers:
    - pager: delta --dark --syntax-theme=tokyonight_night --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
gui:
  theme:
    activeBorderColor:
      - "#ff9e64"
      - bold
    inactiveBorderColor:
      - "#27a1b9"
    searchingActiveBorderColor:
      - "#ff9e64"
    optionsTextColor:
      - "#7aa2f7"
    selectedLineBgColor:
      - "#283457"
    cherryPickedCommitBgColor:
      - "#283457"
    cherryPickedCommitFgColor:
      - "#7aa2f7"
    unstagedChangesColor:
      - "#db4b4b"
    defaultFgColor:
      - "#c0caf5"
