import = [
    "~/.config/alacritty/themes/themes/tokyo-night-storm.toml"
]

[env]
TERM = "alacritty"

[font]
size = 12

[font.bold]
family = "0xProto Nerd Font Mono"
style = "Bold"

[font.italic]
family = "0xProto Nerd Font Mono"
style = "Italic"

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true

[window.padding]
x = 0
y = 0
