theme="tokyonight"

[editor]
true-color = true
insert-final-newline = false
text-width = 80
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"

[editor.soft-wrap]
enable = true
wrap-at-text-width = false
wrap-indicator = ""                                                                                                    

[editor.indent-guides]
render = true
character = "▏"
skip-levels = 1
