#cloud-config

hostname: devbox
timezone: America/Denver

packages:
  - acl
  - attr
  - autoconf
  - automake
  - dnsmasq-base
  - git
  - libacl1-dev
  - libcap-dev
  - liblxc1
  - liblxc-dev
  - libsqlite3-dev
  - libtool
  - libudev-dev
  - liblz4-dev
  - libuv1-dev
  - make
  - pkg-config
  - rsync
  - squashfs-tools
  - tar
  - tcl
  - xz-utils
  - ebtables
  - lvm2
  - thin-provisioning-tools
  - btrfs-progs
  - busybox-static
  - curl
  - gettext
  - jq
  - sqlite3
  - socat
  - bind9-dnsutils
  - qemu-system-x86
  - nfs-kernel-server
  - python3-venv
  - shellcheck
  - flake8
  - python3-pip

package-update: true
package-upgrade: true

groups:
  - kadin
  - adm
  - systemd-journal
  - netdev
  - lxd
  - landscape
  - ceph
  - libvirt
  - microk8s

users:
  - default
  - name: kadinsayani
    gecos: Kadin Sayani
    primary_group: kadin
    groups:
      - lxd
      - microk8s
      - adm
      - systemd-journal
    lock_passwd: true
    shell: /bin/bash
    sudo: "ALL=(ALL) NOPASSWD:ALL"
    uid: "1000"
    ssh_import_id:
      - lp:kadinsayani
      - gh:kadinsayani

ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEu+RmEYG8tthh/JeWu/5Ch/0qU+HIxMFQUXWRvBehlM kadin.sayani@canonical.com

write_files:
  - content: |
      GOPATH=$(go env GOPATH)
      export PATH=$PATH:/opt/go/bin:$GOPATH/bin:~/minio

      export LXD_SHIFTFS_DISABLE=true
      export CGO_CFLAGS="-I${GOPATH}/deps/dqlite/include/"
      export CGO_LDFLAGS="-L${GOPATH}/deps/dqlite/.libs/"
      export LD_RUN_PATH="${GOPATH}/deps/dqlite/.libs/"
      export CGO_LDFLAGS_ALLOW="(-Wl,-wrap,pthread_create)|(-Wl,-z,now)"

      alias cdlxd='cd ~/lxd'
      alias lxd='sudo --preserve-env=PATH,GORACE,LXD_SHIFTFS_DISABLE $GOPATH/bin/lxd'
      alias lxdstart='sudo --preserve-env=PATH,GORACE,LXD_SHIFTFS_DISABLE $GOPATH/bin/lxd --group sudo -v -d'
      alias lxdtest='sudo --preserve-env=PATH,GOPATH,GORACE,LXD_INSPECT,LXD_DEBUG,LXD_VERBOSE,LXD_BACKEND,LXD_NIC_BRIDGED_DRIVER,LXD_CEPH_CLUSTER,LXD_CEPH_CEPHOBJECT_RADOSGW,LXD_CONCURRENT,LXD_SKIP_TESTS,LXD_REQUIRED_TESTS,LXD_SHIFTFS_DISABLE LXD_TMPFS=1 LXD_VERBOSE=1 LXD_NIC_SRIOV_PARENT= LXD_TEST_IMAGE= ./main.sh'
      alias lxdgotest='sudo --preserve-env=GOPATH,CGO_CFLAGS,CGO_LDFLAGS_ALLOW,CGO_LDFLAGS,LD_RUN_PATH,PATH go test ./...'
    path: /etc/skel/.bashrc
    append: true
    permissions: "0750"
  - content: |
      root:1000000:1000000000
    path: /etc/subuid
    append: true
  - content: |
      root:1000000:1000000000
    path: /etc/subgid
    append: true

runcmd:
  - ["su", "kadinsayani", "-c", "mkdir -p /home/kadinsayani/canonical"]
  - [
      "su",
      "kadinsayani",
      "-c",
      "git -C /home/kadinsayani/canonical clone https://github.com/kadinsayani/lxd.git",
    ]
  - [
      "su",
      "kadinsayani",
      "-c",
      "git -C /home/kadinsayani/canonical/lxd remote rm origin",
    ]
  - [
      "su",
      "kadinsayani",
      "-c",
      "git -C /home/kadinsayani/canonical/lxd remote add origin git@github.com:kadinsayani/lxd.git",
    ]
  - git config --global gpg.format ssh
  - git config --global user.email "kadin.sayani@canonical.com"
  - git config --global user.name "Kadin Sayani"
  - git config --global user.signingkey /home/kadinsayani/.ssh/id_ed25519.pub
